id: IEB841BFB
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-23T11:42:51+00:00'
last_modified: '2022-06-07T21:08:41.420841+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG4771
  title: དགོངས་གཅིག་འགྲེལ་པ་ཉི་མའི་སྣང་བ
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    '5519':
      image_group_id: I1KG4822
      title: ''
      total_pages: 458
      order: 1
      base_file: 5519.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
