id: P004216
initial_creation_type: ocr
created_at: 23/03/2020
last_modified_at: 2021-12-17 11:01:54.474474
source_metadata:
  id: bdr:W1KG4771
  title: དགོངས་གཅིག་འགྲེལ་པ་ཉི་མའི་སྣང་བ
  author: ''
  volumes:
    6a37806ae7e34bf589ad1006d8a664b6:
      image_group_id: I1KG4822
      title: ''
      volume_number: 1
      total_pages: 458
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
